export asofcur=me0201
export asofprv=me0112
export asofoth=me0112
export asofcsd=sd020201
export asofanl=me0109
export asofcyc=c10202
echo asofcur
echo $asofcur
echo asofprv
echo $asofprv
echo asofoth
echo $asofoth
echo asofcsd
echo $asofcsd
echo asofanl
echo $asofanl
echo asofcyc
echo $asofcyc
